# This is the CustomResourceDefinition for our EchoServer application.
# You must create this CRD in your k8s cluster prior to running the example.
# To do so, run: `kubectl create -f examples/echo-server/crd.yaml`
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tempnamespaces.example.roperator.com
spec:
  group: example.roperator.com
  versions:
    - name: v1alpha1
      storage: true
      served: true
  scope: Cluster
  subresources:
    status: {}
  names:
    kind: TempNamespace
    plural: tempnamespaces
    singular: tempnamespace
    shortNames:
    - tempns
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            deleteAfter:
              description: 'duration after which to delete the namespace and everything in it. Experessed as a string with 1 or more digits followed by a single character unit of "s" (seconds), "m" (minutes), "h" (hours)'
              type: string
